### PR TITLE
Allow 64bit compilation

### PR DESCRIPTION
**Pull request by DarkaMaul**
Hi,

This pull request is heavily inspired from #67 and introduce the compilation of the challenges for both 32 and 64 bits (64 is the new default).

Due to a lack of time, I only tested on a Debian with both clang and gcc and it worked fine.
I tried to keep changes minimals, feel free to review/edit.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @DarkaMaul! This looks reasonable to me.

One request: could you flip the defaults around so that x86-32 remains the default? I'm not opposed to making x86-64 the default at some point in the future, but I know for a fact that a lot of people currently build from `master` and probably aren't expecting any architectural changes.

**Comment by DarkaMaul** [comment]
Sure, no problem. I also reverted the default build for 32 bits to the `build` directory instead of `build32`.

**Comment by woodruffw** [comment]
Much appreciated! The `clang` build on Windows has been broken for a while, so I'll ignore that and merge when the rest of the jobs go through. Thanks again.

**Comment by m3lixir** [comment]
Closes #14 #67

**Pull request merged**
